---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/22/24 7:03 PM
---

AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile( "shared.lua" )

include( 'shared.lua' )


---SetItem
---@param itemData table
function ENT:SetItem(itemData, quantity)
    self.Item = itemData;

    self:SetQuantity(quantity);
    self:SetItemName(itemData and itemData.Name or "");
end

---GetItem
---@return table
function ENT:GetItem()
    return self.Item;
end