---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/22/24 7:03 PM
---

AddCSLuaFile( "cl_init.lua" )
AddCSLuaFile( "shared.lua" )

include( 'shared.lua' )

function ENT:Use( activator )
    local item = self:GetItem();

    if (not item or not IsValid(activator)) then return end

    local entId = activator:EntIndex();

    local mainHand = getEquipmentSlot(entId,"Main Hand");
    local offHand = getEquipmentSlot(entId,"Off Hand");

    if (not mainHand) then
        activator:EquipItem(item,"Main Hand")
        self:Remove();
    elseif (not offHand) then
        activator:EquipItem(item,"Off Hand")
        self:Remove();
    else
        --TODO: Add to inventory
    end
end

---SetItem
---@param itemData table
function ENT:SetItem(itemData, quantity)
    self.Item = itemData;

    self:SetQuantity(quantity);
    self:SetItemName(itemData and itemData.name or "");
end

---GetItem
---@return table
function ENT:GetItem()
    return self.Item;
end