---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/22/24 7:03 PM
---

DEFINE_BASECLASS( "c13_base" );

ENT.PrintName		= "C13_BASE_ITEM";
ENT.Author			= "The Maw";
ENT.Purpose			= "Provides base fundamentals for City 13 items. Dropped items inherit this class!";

---SetupDataTables
function ENT:SetupDataTables()
    BaseClass.SetupDataTables(self);

    self:NetworkVar("Int", 0, "Quantity");
    self:NetworkVar("String", 0, "ItemName");

    if (SERVER) then
        self:SetQuantity(1);
        self:SetItemName("N/A");
    end
end