---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 10:39 PM
---

AddCSLuaFile();

DEFINE_BASECLASS( "c13_base_appliance" );


ENT.PrintName		= "C13 Test Appliance";
ENT.Author			= "The Maw";
ENT.Purpose			= "Test Appliance";

ENT.Durability      = 100
ENT.PowerRequired   = 2;