---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 1/5/25 7:29 PM
---

---AddLuaCSFolder
---@param directory string
function addLuaCSFolder(directory)
    local Dir 		= GM.Folder:gsub("gamemodes/","").."/gamemode/"
    local files 	= file.Find(Dir.. directory .."/*.lua","LUA")

    for _,v in pairs( files ) do
        if (CLIENT) then include(Dir.. directory .."/"..v)
        else AddCSLuaFile(Dir.. directory .."/"..v) end
    end
end

---AddLuaSVFolder
---@param directory string
function addLuaSVFolder(directory)
    local Dir 		= GM.Folder:gsub("gamemodes/","").."/gamemode/"
    local files	= file.Find(Dir.. directory .."/*.lua","LUA")

    for _,v in pairs( files ) do
        if (SERVER) then include(Dir.. directory .."/"..v) end
    end
end

---AddLuaSHFolder
---@param directory string
function addLuaSHFolder(directory)
    local Dir 		= GM.Folder:gsub("gamemodes/","").."/gamemode/"
    local files 	= file.Find(Dir.. directory .."/*.lua","LUA")

    for _,v in pairs( files ) do
        if (SERVER) then AddCSLuaFile(Dir.. directory .."/"..v) end
        include(Dir.. directory .."/"..v)
    end
end