---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 1/4/25 11:38 AM
---

bagGUI = bagGUI or nil;

---openBag
---@param containerItem ITEM
---@return nil
function openBag(containerItem)
    if (not bagGUI) then
        bagGUI = vgui.Create("C13_Bag");
        bagGUI:SetSize(500, 500);
        bagGUI:SetTitle(containerItem.name);
        bagGUI:MakePopup();
        bagGUI:Center();
    end

    bagGUI:setItem(containerItem);
    bagGUI:SetVisible(true);
end