---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/25/24 6:34 PM
---

equipmentMenu = equipmentMenu or nil;

local sh = ScrH();

if (not equipmentMenu) then
    equipmentMenu = vgui.Create("C13_Equipment")
    equipmentMenu:SetPos(50, sh / 2 - 200);
    equipmentMenu:SetSize(400,400);
    equipmentMenu:InvalidateLayout();
    equipmentMenu:SetVisible(false);
end

function GM:OnSpawnMenuOpen()
    if (not equipmentMenu) then return end;

    equipmentMenu:ReloadEquipment(LocalPlayer());
    equipmentMenu:SetVisible(true);
    equipmentMenu:MakePopup();
end

function GM:OnSpawnMenuClose()
    equipmentMenu:SetVisible(false);
end

function reloadEquipmentMenu(entIndex)
    if (not equipmentMenu or not equipmentMenu:IsVisible()) then return end

    local pl = LocalPlayer();

    if (pl:EntIndex() ~= entIndex) then return end;

    equipmentMenu:ReloadEquipment(pl);
end