---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/21/24 9:06 PM
---
---
local sh = ScrH();

local chatW, chatH = 500, 300;
local cx, cy = 50, sh - 500;

chatBox = chatBox or nil;

---openChatbox
local function openChatbox()
    if (not chatBox) then
        chatBox = vgui.Create("C13_Chatbox")
        chatBox:SetPos(cx, cy);
        chatBox:SetSize(chatW, chatH)
    end

    chatBox:open();
end

hook.Add("PlayerBindPress", "c13_chatBinds", function(_, bind, _)
    ---@type boolean
    local bTeam;

    if (bind == "messagemode") then
        bTeam = false;
    elseif (bind == "messagemode2") then
        bTeam = true
    else
        return
    end

    openChatbox();

    return true;
end)

---ChatText
---@param _ number
---@param _ string
---@param text string
---@param type string
function GM:ChatText(_, _, text, type)
    if type == "joinleave" or type == "none" then
        chatBox.RichText:AppendText(text .. "\n")
    end
end


-- OVERRIDE THE OLD CHAT TEXT TO INJECT OUR OWN CODE. From Wiki Garrysmod <---
local oldAddText = chat.AddText;

---AddText
function chat.AddText(...)
    local args = { ... } -- Create a table of varargs

    for _, obj in ipairs(args) do
        if type(obj) == "table" then
            -- We were passed a color object
            chatBox.RichText:InsertColorChange(obj.r, obj.g, obj.b, 255)
        elseif type(obj) == "string" then
            -- This is just a string
            chatBox.RichText:AppendText(obj)
        elseif obj:IsPlayer() then
            local col = GAMEMODE:GetTeamColor(obj) -- Get the player's team color
            chatBox.RichText:InsertColorChange(col.r, col.g, col.b, 255) -- Make their name that color
            chatBox.RichText:AppendText(obj:Nick())
        end
    end

    -- Gotta end our line for this message
    chatBox.RichText:AppendText("\n")

    -- Call the original function
    oldAddText(...)
end

