---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/25/24 4:33 PM
---

jobPicker = jobPicker or nil;

if (not jobPicker) then
    jobPicker = vgui.Create("C13_JobPicker")
    jobPicker:SetWide(600);
    jobPicker:Dock(LEFT);
    jobPicker:InvalidateLayout();
    jobPicker:MakePopup();
end

---reloadJobPickerHUD
function reloadJobPickerHUD()
    jobPicker:PopulateJobsPanel();
    jobPicker:SetVisible(true);
end