---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/25/24 6:36 PM
---



local PANEL = {}

local IsValid = IsValid;
local setDrawColor = surface.SetDrawColor;
local drawRect = surface.DrawRect;

local default_icon = Material("vgui/avatar_default");

---Init
function PANEL:Init()
    self.scrollablePanel = vgui.Create("DScrollPanel",self);
    self.scrollablePanel:Dock( FILL );
end

---Paint
---@param w number
---@param h number
function PANEL:Paint(w,h)
    setDrawColor(MAIN_BG_COLOR.r, MAIN_BG_COLOR.g, MAIN_BG_COLOR.b, MAIN_BG_COLOR.a);
    drawRect(0,0,w,h);
end

---PerformLayout
---@param _ number
---@param _ number
function PANEL:PerformLayout(_, _)
end

function PANEL:ReloadEquipment(entity)
    if (not IsValid(entity)) then return end

    self.scrollablePanel:Clear();

    local entIndex = entity:EntIndex();
    local equipment = getEquipmentSlots();

    for slotId,slotName in pairs(equipment) do
        local item = getEquipmentSlot(entIndex, slotId);

        local slotPanel = self.scrollablePanel:Add("DPanel");
        slotPanel:Dock(TOP);
        slotPanel.Paint = function() end;

        local slot = vgui.Create("DButton", slotPanel)
        slot:Dock(LEFT);
        slot:SetWide(slot:GetTall() + 2);

        if (item and item.icon) then
            slot:SetMaterial(item.icon)
        else
            slot:SetMaterial(default_icon);
        end

        slot.DoClick = function(_)
            print("Click equipment ID ", slotId, slotName);
        end

        local label = vgui.Create("DLabel", slotPanel);
        label:SetText(slotName);
        label:Dock(FILL);

        if (item) then
            label:SetText(slotName .. " - " .. item.name);
        end
    end
end


vgui.Register( "C13_Equipment", PANEL, "DPanel" );