---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 1/4/25 3:13 AM
---

local PANEL = {}

local IsValid = IsValid;

local setDrawColor = surface.SetDrawColor;
local drawRect = surface.DrawRect;

local simpleText = draw.SimpleText;

---Init
function PANEL:Init()
    self.Font 		= "c13_scoreboard"
    self.Text		= ""
    self.bannerH    = 100

    self:SetPaintBackgroundEnabled(false)
    self:SetPaintBorderEnabled(false)

    self:DockPadding( 5, self.bannerH, 5, 5 )

    self.Pane = vgui.Create("DScrollPanel", self)
    self.Pane:Dock(FILL)
    self.Pane.Paint = function(_, _, _)
    end

    self.Pane.VBar.Paint = function(_, _, _)
    end
    
    self.Pane.VBar.btnGrip.Paint = function(_, w, h)
        setDrawColor(MAIN_SCOREBOARD_TEXT)
        drawRect(2, 2, w - 4, h - 4, MAIN_SCOREBOARD_TEXT)
    end
    self.Pane.VBar.btnDown.Paint = self.Pane.VBar.btnGrip.Paint
    self.Pane.VBar.btnUp.Paint = self.Pane.VBar.btnGrip.Paint

    self.List = vgui.Create("DListLayout", self.Pane)
    self.List:Dock(FILL)
end

---SetTitle
---@param title string
function PANEL:SetTitle( title )
    self.Text = title
end

---SetFont
---@param font string
function PANEL:SetFont( font )
    self.Font = font
end

---populate
function PANEL:populate()
    self.List:Clear()

    for _,v in pairs(player.GetAll()) do
        local a = self.List:Add("DPanel")
        a:SetText("")
        a:SetTall(22)
        a.Paint = function(_, W, H)
            if (not IsValid(v)) then return end

            setDrawColor(MAIN_BG_COLOR);
            drawRect(0,0,W,H);

            simpleText(v:Nick(),"c13_normal",10,H/2,MAIN_TEXT_COLOR,nil,1)
            simpleText(v:Ping(),"c13_normal",W-13,H/2,MAIN_TEXT_COLOR,2,1)
        end
    end
end

---Paint
---@param _ number
---@param _ number
function PANEL:Paint(_, _)
    --setDrawColor(MAIN_BG_COLOR.r, MAIN_BG_COLOR.g, MAIN_BG_COLOR.b, MAIN_BG_COLOR.a);
    --drawRect(0,0,w,h);
end

---PaintOver
---@param w number
---@param _ number
---@return boolean
function PANEL:PaintOver(w, _)
    if (not self.Text or #self.Text <= 0) then return true end

    simpleText(self.Text,self.Font,w/2,self.bannerH/2,MAIN_TEXT_COLOR,1,1)

    return true
end

vgui.Register("C13_Scoreboard", PANEL, "DPanel");