---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 9:30 PM
---

AddCSLuaFile("itembase.lua")
AddCSLuaFile("itemmanager.lua")

include("itembase.lua")
include("itemmanager.lua")

local Folder  		= GM.Folder:gsub("gamemodes/","").."/gamemode/sh_items/items";

---@type table
local classes		= {};

local Class   		= file.Find(Folder.."/*.lua","LUA");
local copy          = table.Copy;

for _,v in pairs(Class) do
    CLASS = {};

    AddCSLuaFile(Folder.."/"..v);
    include(Folder.."/"..v);

    setmetatable( CLASS, getBaseClass() );

    CLASS.__index = CLASS;

    classes[CLASS.name] = copy(CLASS);

    print("Loading ITEM " .. CLASS.name);
end

---getItemClass
---@param itemClass string
---@return table
function getItemClass(itemClass)
    return classes[itemClass];
end