---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 9:34 PM
---

local insert = table.insert;

---@type table
local BASECLASS = {
    --@Variables
    icon = Material("vgui/avatar_default"),
    properties = {},

    weight = 1,
    volume = 1,
    maxVolume = 0,

    isContainer = false,
    parentContainer = nil,

    -- Gets all the items in the container
    getItems = function(self)
        if (not self.items or not self.isContainer) then return {} end
        return self.items;
    end,

    -- Gets the current total volume of the item and the items it contains, if any.
    getVolume = function(self)
        if (not self.items or not self.isContainer) then return self.volume end

        local currentVolume = self.volume;

        for _, item in pairs(self.items) do
            currentVolume = currentVolume + item:getVolume();
        end

        return currentVolume;
    end,

    -- Adds items to the container and returns the leftover items, if any.
    addItems = function(self, items)
        if (not self.isContainer) then return items end
        self.items = self.items or {};

        local currentVolume = self:getVolume();

        -- Only when adding items, should you consider the volume upstream.
        if (self.parentContainer) then
            currentVolume = currentVolume + self.parentContainer:getVolume();
        end

        for id, item in pairs(items) do
            local itemVolume = item:getVolume();

            if (currentVolume + itemVolume < self.maxVolume) then
                currentVolume = currentVolume + itemVolume;
                item.parentContainer = self;
                insert(self.items,item);
                items[id] = nil;
            end
        end

        return items;
    end,

    --@Model
    getModel = function(self)
        return self.Model or "models/error.mdl"
    end,

    setModel = function(self,model)
        self.Model = model
    end,


    --@Basics
    getClass = function(self)
        return self.Name or "_C13_BASE"
    end,

    getID = function(self)
        return self.ID
    end,

    getIcon = function(self)
        return self.Icon
    end,

    init 		= function(_) end,

    use         = function(_) end,
}

BASECLASS.__index = BASECLASS


---getBaseClass
---@return table
function getBaseClass()
    return BASECLASS;
end