---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 9:44 PM
---

---@type function
local insert = table.insert;

---@type userdata
local itemsInGame = {};

---createItem
---@param className string
---@param itemID number
function createItem(className,itemID)
    local itemClass = getItemClass(className);

    if (not itemClass) then error( "Invalid ITEM class: " .. className .. "!" ) return end

    local item = {
    _Region = SystemID,
    Name = ClassName,
    }

    setmetatable( item, itemClass )

    itemID = itemID or insert(itemsInGame, item);

    itemsInGame[itemID] = item
    itemsInGame[itemID].ID = itemID;
    itemsInGame[itemID]:init();

    return itemsInGame[itemID];
end

---removeItem
---@param item userdata
function removeItem(item)
    removeItemByID(item:getID());
end

---removeItemByID
---@param ID number
function removeItemByID(ID)
    itemsInGame[ID] = nil;
end