---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 8:28 PM
---

MAIN_TEXT_COLOR = Color(255,255,255);

-- Health states
MAIN_HEALTH_COLOR_GREAT = Color(0,255,0);
MAIN_HEALTH_COLOR_GOOD = Color(100,155,0);
MAIN_HEALTH_COLOR_BAD = Color(155,100,0);
MAIN_HEALTH_COLOR_TERRIBLE = Color(200,55,0);
MAIN_HEALTH_COLOR_CRITICAL = Color(255,0,0);

-- UI background color
MAIN_HEALTH_BG_COLOR = Color(0,0,0,200);