---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 8:50 PM
---

surface.CreateFont( "HealthFont", {size = 22, weight = 0, antialias = false, font = "Roboto-Bold", shadow = true} )

surface.CreateFont( "c13_normal", {size = 18, weight = 0, antialias = false, font = "Roboto-Regular"} )