---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 1/4/25 11:13 AM
---


if (SERVER) then
    util.AddNetworkString("requestOpenBag");
    util.AddNetworkString("transmitBag");

    net.Receive("requestOpenBag", function(_, pl)
        local itemId = net.ReadUInt(32);

        -- The player provided no valid itemID
        if (not itemId) then
            return
        end

        print("Requested to open bag item", itemId, pl:Nick(), pl:SteamID64());

        local itemData = getItemByID(itemId);

        -- The item doesn't exist in the game world.
        if (not itemData or not itemData.isContainer) then
            return
        end

        local ownsItem = isItemHeldByEntId(pl:EntIndex(), itemId);

        -- Check if the player is actually holding this item anywhere on him.
        if (not ownsItem) then
            return
        end

        net.Start("transmitBag")
        net.WriteTable(itemData);
        net.Send(pl);
    end)
else
    net.Receive("transmitBag", function()
        local containerItem = net.ReadTable();
        openBag(containerItem);
    end)

    ---requestOpenBag
    ---@param itemId number
    function requestOpenBag(itemId)
        if (not itemId) then
            return
        end

        net.Start("requestOpenBag")
        net.WriteUInt(itemId, 32);
        net.SendToServer();
    end
end