---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 9:13 PM
---

serverEquipment = serverEquipment or {};

local type = type;
local top = Vector(0,0,20);
-- This should be universal for every object, not just players.
local meta = FindMetaTable("Entity");

local slotIDs = {};
slotIDs[1] = "Head";
slotIDs[2] = "Headset";
slotIDs[3] = "Backpack";
slotIDs[4] = "Shoulder";
slotIDs[5] = "Hands";
slotIDs[6] = "Foot";
slotIDs[7] = "Body";
slotIDs[8] = "Legs";
slotIDs[9] = "Main Hand";
slotIDs[10] = "Off Hand";

local slotNameToIDs = {}

--- Reverse the IDs to a NameToID map for speedier performance.
for k,v in pairs(slotIDs) do
    slotNameToIDs[v:lower()] = k;
end

---equipment_translateID
---@param id number
---@return string
function equipment_translateID(id)
    return slotIDs[id];
end

---equipment_translateName
---@param name string
---@return number
function equipment_translateName(name)
    name = name:lower();
    return slotNameToIDs[name];
end

if SERVER then
    -- Serverside nets
    util.AddNetworkString("EquipItem")
    util.AddNetworkString("UnequipItem")
    util.AddNetworkString("ClearEquipment")
    util.AddNetworkString("TransmitEquipment")

    ---EquipItem
    ---@param item table
    function meta:EquipItem(item,slot)
        local entId = self:EntIndex();

        slot = slot and slot or item.Slot;
        slot = slot and slot or "Main Hand";

        local slotId = equipment_translateName(slot);

        if (not slotId) then return end;

        serverEquipment[entId] = serverEquipment[entId] or {};

        -- Unequip the item if there is something on the slot.
        if (serverEquipment[entId][slotId]) then
            self:UnequipItem(serverEquipment[entId][slotId]);
        end

        serverEquipment[entId][slotId] = item;
    end

    ---UnequipItem
    ---@param item table
    function meta:UnequipItem(item, slot)
        local entId = self:EntIndex();
        if (not serverEquipment[entId]) then return end;

        slot = slot and slot or item.Slot;
        slot = slot and slot or "Main Hand";

        local slotId = equipment_translateName(slot);
        if (not slotId) then return end;

        -- Drops the item on the entity's position.
        SpawnItem(self:GetPos() + top, item,1);

        serverEquipment[entId][slotId] = nil;
    end

else
    net.Receive("EquipItem",function()
        local entId = net.ReadUInt(32);
        local slotId = net.ReadUInt(7);
        local item = net.ReadTable(); -- SHOULD THE CLIENT REALLY KNOW ALL THIS?

        serverEquipment[entId][slotId] = item;
    end)

    net.Receive("UnequipItem",function()
        local entId = net.ReadUInt(32);
        local slotId = net.ReadUInt(7);

        serverEquipment[entId][slotId] = nil;
    end)

    net.Receive("TransmitEquipment",function()
        local entId = net.ReadUInt(32);
        local equipment = net.ReadTable(); -- SHOULD THE CLIENT REALLY KNOW ALL THIS?

        serverEquipment[entId] = equipment;
    end)

    net.Receive("ClearEquipment",function()
        local entId = net.ReadUInt(32);

        serverEquipment[entId] = nil;
    end)
end

---getEquipment
---@param entId number
---@return table
function getEquipment(entId)
    return serverEquipment[entId] or {};
end

---getEquipmentSlot
---@param entId number
---@param name string
---@return table
function getEquipmentSlot(entId,name)
    if (type(name) == "string") then name = equipment_translateName(name) end
    return getEquipment(entId)[name];
end

---clearEquipment
---@param entId number
function clearEquipment(entId)
    serverEquipment[entId] = nil;
end