---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/28/24 5:41 PM
---

---@type number
local roundCountDown;

---@type boolean
local gameOn = false;

local CurTime = CurTime;
local floor = math.floor;
local IsValid = IsValid;

local defaultStartTime = 120;

if (SERVER) then
    util.AddNetworkString("RoundStart")

    hook.Add("PlayerInitialSpawn", "c13_updateRoundTimer", function(pl)
        updateRoundTimer(pl);
    end)

    ---restartRound
    function restartRound()
        ---@type number
        local now = CurTime();

        roundCountDown = now + defaultStartTime;
        gameOn = false;

        updateRoundTimer();
    end

    hook.Add("Tick", "c13_gameCounter", function()
        if (gameOn) then
            return
        end ;

        local now = CurTime();

        if (not roundCountDown) then
            restartRound();
            return
        end ;

        if (roundCountDown < now) then
            for _, pl in pairs(player.GetAll()) do
                pl.allowSpawn = true;
                pl:Spawn();
            end

            gameOn = true;
        end
    end);

    ---updateRoundTimer
    ---@param pl userdata
    function updateRoundTimer(pl)
        local now = CurTime();
        if (not roundCountDown or roundCountDown < now) then
            return
        end

        net.Start("RoundStart");
        net.WriteUInt(floor(roundCountDown - now), 8);

        if (IsValid(pl)) then
            net.Send(pl);
        else
            net.Broadcast();
        end
    end
else
    net.Receive("RoundStart", function()
        ---@type number
        local now = CurTime();

        ---@type number
        local duration = net.ReadUInt(8);

        roundCountDown = now + duration;
    end)
end

---getRoundStarted
---@return number
function getRoundCountdown()
    return roundCountDown;
end

---getRoundStarted
---@return boolean
function getRoundStarted()
    ---@type number
    local now = CurTime();
    return roundCountDown < now;
end