---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 7:29 AM
---

local table = table;

---intersect
---@param t1 table
---@param t2 table
---@return table
---@public
function table.intersect(t1, t2)
    local ret = {}

    for k, _ in pairs(t2) do
        if t1[k] ~= nil then
            ret[k] = t1[k]
        end
    end

    return ret;
end