---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 12:51 PM
---

CLASS.name 				= "Headset Combine";
CLASS.Model             = "models/props_lab/clipboard.mdl";

CLASS.slot              = "Headset";
CLASS.channels          = {
    [":a"] = "Combine",
    [":c"] = "Common",
}