---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 12:55 PM
---

CLASS.Name 				= "Headset Science";
CLASS.Model             = "models/props_lab/clipboard.mdl";

CLASS.slot              = "Headset";
CLASS.channels          = {
    [":r"] = "Science",
    [":c"] = "Common",
}