---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 7:07 AM
---

CLASS.name 				= "Headset Common";
CLASS.Model             = "models/props_lab/clipboard.mdl";

CLASS.slot              = "Headset";
CLASS.channels          = {
    [":c"] = "Common",
}