---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 12:54 PM
---

CLASS.Name 				= "Headset Medical";
CLASS.Model             = "models/props_lab/clipboard.mdl";

CLASS.slot              = "Headset";
CLASS.channels          = {
    [":m"] = "Medical",
    [":c"] = "Common",
}