---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 12:52 PM
---

CLASS.name 				= "Headset Logistics";
CLASS.Model             = "models/props_lab/clipboard.mdl";

CLASS.slot              = "Headset";
CLASS.channels          = {
    [":l"] = "Logistics",
    [":c"] = "Common",
}