---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/21/24 6:17 PM
---

local insert = table.insert;
local CurTime = CurTime;

local entityWithEffects = {};
local lastRun;

---applyEffect
---@param entity userdata
---@param dataEffect void
---@param duration number
function applyEffect(entity, dataEffect, duration)
    -- Duration is less or equal to 0, so no effect will apply?
    if (duration <= 0) then
        return
    end

    -- It is possible to apply an effect without an entity, such as other items.
    dataEffect.Entity = entity;
    dataEffect.EndTime = CurTime() + duration;
    dataEffect.LastTime = CurTime();

    insert(entityWithEffects, dataEffect);
end

---tickEffect
local function tickEffect()
    local timeNow = CurTime();

    if (lastRun and lastRun > timeNow) then
        return
    end

    -- Don't run more than twice in 1 second. Performance reasons.
    lastRun = timeNow + 1;

    for id, data in pairs(entityWithEffects) do
        local pickTime = timeNow;

        -- This will cap delta to the EndTime of the effect, rather than overextend.
        if (data.EndTime <= timeNow) then
            pickTime = data.EntTime;
        end

        -- Calculate delta for effect multiplier
        local delta = pickTime - data.LastTime;
        data.LastTime = pickTime;

        -- If there is a tick to run, then run it.
        if (data.Tick) then
            data.Tick(delta, data);
        end

        -- If the effect has expired, remove it from the watchlist.
        if (data.EndTime <= timeNow) then
            entityWithEffects[id] = nil;
        end
    end
end

hook.Add("Tick", "effectTicks", tickEffect);