---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/22/24 2:57 PM
---


hook.Add( "PlayerCanSeePlayersChat", "CheckPlayerChannelsC13", function(text, bTeam, plReceiver, plSpeaker)
    -- TODO: Need to filter out the channels the listener and speaker is talking in.
    print(text,bTeam,plReceiver,plSpeaker);
end)
