---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/20/24 10:41 PM
---

local concat = table.concat;
local create = ents.Create;
local isValid = IsValid;
local explode = string.Explode;
local len = string.len;
local tostring = tostring;

---The chat commands function
chatCommands = chatCommands or {}

---addChatCommand
---@param command string
---@param funcCallback function
function addChatCommand(command,funcCallback)
    chatCommands["/"..command:gsub(" ","_"):lower()] = funcCallback
end

hook.Add( "PlayerSay", "ChatCommandsC13", function( ply, text, _ )
    local args = explode(" ",text)
    local command = args[1]:lower();

    if (chatCommands[command]) then
        chatCommands[command](ply,concat(args," ",2))
        return false;
    end
end)

addChatCommand("spawn",function(pl,str)
    if (not pl:IsAdmin()) then return end

    local e = create(str)

    if (not isValid(e)) then return end

    e:SetPos(pl:GetEyeTrace().HitPos + Vector(0,0,20))
    e:Spawn()
    e:Activate()
    e:DropToFloor()
end)

addChatCommand("spawnitem",function(pl,str)
    if (not pl:IsAdmin()) then return end

    local item = createItem(str);

    if (not item) then pl:ChatPrint("Item does not exist!") return end;

    local pos = pl:GetEyeTrace().HitPos + Vector(0,0,20);

    pl:ChatPrint("Spawn item " .. item.Name .. " at " .. tostring(pos));

    SpawnItem(pos,item,1);
end)

addChatCommand("respawn",function(pl,str)
    local tPl;

    if (str and len(str) > 0 and pl:IsAdmin()) then
        tPl = player.GetBySteamID64(str);
    end

    if (isValid(tPl) and (not tPl:Alive() or tPl:GetObserverMode() ~= OBS_MODE_NONE)) then
        tPl.allowSpawn = true;
        tPl:Spawn();
    elseif (pl:GetObserverMode() ~= OBS_MODE_NONE and pl:IsAdmin()) then
        pl.allowSpawn = true;
        pl:Spawn();
    elseif (not pl:Alive()) then
        pl:Spawn();
    end
end)