---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/24/24 9:26 AM
---

GAME_CONFIG = GAME_CONFIG or {};

-- THE CONFIG DIRECTORY
local configDir = "c13";

-- LOCATION OF CUSTOM CONFIG
local configLocation = configDir .. "/config.json";

-- LOCATION OF DEFAULT CONFIG. DO NOT CHANGE THIS FOR COMPARTIBILITY'S SAKE
local baseConfigLocation = configDir .. "/config_default.json";

---initializeConfig
local function initializeConfig()
    local modDefault = "data/"..baseConfigLocation;
    local modConfig = "data/"..configLocation;

    if (not file.Exists(modDefault,"GAME")) then error("Default configuration not found!") return end
    if (not file.IsDir( configDir, "DATA" )) then file.CreateDir(configDir) end;

    local json = "";

    if (file.Exists(modConfig,"GAME")) then
        print("Loading NORMAL configurations from file ", modConfig);
        json = file.Read(modConfig,"GAME");
    else
        print("Loading DEFAULT configurations from file ", modDefault);
        json = file.Read(modDefault,"GAME");

        print("Copied DEFAULT configurations to file ", modConfig);
        file.Write(configLocation,json);
    end

    GAME_CONFIG = util.JSONToTable(json);
end

hook.Add("Initialize", "c13LoadConfig", initializeConfig);

---getConfigSetting
---@param key string
---@return any
function getConfigSetting(key)
    return GAME_CONFIG[key];
end