---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by themaw.
--- DateTime: 12/21/24 1:27 AM
---

---PlayerDeathSound
---@param _ userdata
---@return boolean
function GM:PlayerDeathSound(_)
    return true
end

---PlayerDeathThink
---@param _ userdata
---@return any
function GM:PlayerDeathThink(_)
    return true;
end
